config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  
  get "home/index"
  get 'previous_commitments', to: 'commitments#previous', as: :previous_commitments
  
  resources :tasks do
    get :activities, on: :collection
    member do
      patch 'mark_completed'
      patch 'archive'
      patch 'unarchive'
    end
  end
  
  resources :categories
  resources :commitments
  devise_for :users

  get 'charts', to: 'charts#index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @tasks = Task.joins(commitment: :user).where(users: { id: current_user.id }).where(commitments: { active: true })
  end
end

app/views/home/index.html.erb
<div class="container">
  <main class="animate-up delay-2">
    <h1 class="sr-only">Trabalhos</h1>
    <% if @tasks.any? %>
      <div class="cards">
        <% @tasks.each_with_index do |task, index| %>
          <div class="card group relative grid grid-cols-6 gap-4 mb-2 p-8 transition-all border rounded items-center <%= task.status == "in_progress" ? "bg-white duration-200 hover:bg-gradient-to-r from-orange-100 to-white border-slate-300" : "" %> <%= task.status == "archived" ? "bg-slate-300 text-slate-400 border-slate-300" : "" %> <%= task.status == "completed" ? "bg-green-300 text-green-600 border-green-400" : "" %>" data-id="<%= task.id %>">
            <div class="col-span-2 text-start">
              <%= link_to task_path(task.id), data: { turbo_frame: "modal" } do %>  
                <div class="flex gap-4 items-center">
                  <span><%= index + 1 %></span>
                  <div class="text-xl font-semibold"><%= task.title %></div>
                </div>
              <% end %>
            </div>
            <div class="col-span-1">
              <span class="block text-xs font-semibold uppercase">Horas Alocadas</span>
              <p class="font-semibold"><%= task.formatted_hours %></p>
            </div>
            <div class="col-span-1">
              <span class="block text-xs font-semibold uppercase">Categoria</span>
              <p class="font-semibold"><%= task.category.name %></p>
            </div>
            <div class="col-span-1 flex items-center justify-center font-semibold">      
              <% case task.status %>
              <% when "archived" %>
                <div class="text-slate-400">
                  Arquivada
                </div>
              <% when "completed" %>
                <div class="text-green-600">
                  Concluída
                </div>
              <% else %>
                <div class="text-blue-600">
                  Em andamento
                </div>
              <% end %>
            </div>
            <div class="col-span-1 justify-end items-center gap-3 hidden group-hover:flex">
              <p class="sr-only">Ações</p>
              <% if task.status == 'archived' %>
                <%= button_to lucide_icon('archive-restore', class: 'text-slate-400 hover:text-slate-500 justify-center items-center'), unarchive_task_path(task), method: :patch, title: 'Desarquivar Tarefa' %>
              <% elsif task.status == 'completed' %>
              <% else %>
                <%= button_to lucide_icon('check-check', class: 'text-green-500 hover:text-green-600 items-center justify-center '), mark_completed_task_path(task.id), method: :patch, title: 'Marcar como concluída', class: "mt-2" %>
                <%= button_to lucide_icon('archive', class: 'text-gray-500 hover:text-gray-600 items-center justify-center '), archive_task_path(task), method: :patch, title: 'Arquivar Tarefa', class: "mt-2" %>
                <%= link_to lucide_icon('edit', class: 'text-blue-500 hover:text-blue-600 items-center justify-center '), edit_task_path(task.id), title: 'Editar Tarefa' %>
                <%= button_to lucide_icon('trash', class: 'text-red-500 hover:text-red-600 items-center justify-center '), task_path(task.id), method: :delete, data: { confirm: 'Você tem certeza que deseja excluir esta tarefa?' }, title: 'Remover Tarefa' %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <h1 class="font-bold text-center items-center text-4xl p-8">
        Não há dados cadastrados.
      </h1>
    <% end %>
  </main>
</div>