config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  
  get "home/index"
  get 'previous_commitments', to: 'commitments#previous', as: :previous_commitments
  
  resources :tasks do
    get :activities, on: :collection
    member do
      patch 'mark_completed'
      patch 'archive'
      patch 'unarchive'
    end
  end
  
  resources :categories
  resources :commitments
  devise_for :users

  get 'charts', to: 'charts#index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/models/commitment.rb
class Commitment < ApplicationRecord
  belongs_to :user

  has_many :tasks, dependent: :destroy
  has_many :task_histories, dependent: :destroy

  validates :description, presence: true
  validates :progress, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }

  def update_progress
    total_tasks = tasks.size
    return self.progress = 0 if total_tasks.zero?

    completed_tasks = tasks.select(&:completed?).size
    self.progress = (completed_tasks.to_f / total_tasks * 100).round(2)
    save
  end

  def time_remaining
    remaining_time = created_at + 7.days - Time.current
    return "Expirado" if remaining_time <= 0

    days = (remaining_time / 1.day).to_i
    hours = ((remaining_time % 1.day) / 1.hour).to_i

    days_text = days == 1 ? "#{days} dia" : "#{days} dias"
    hours_text = hours == 1 ? "#{hours} hora" : "#{hours} horas"

    "#{days_text} e #{hours_text}"
  end
end

app/controllers/commitments_controller.rb
class CommitmentsController < ApplicationController
  before_action :set_commitment, only: %i[ show edit update destroy ]

  # GET /commitments or /commitments.json
  def index
    @commitments = Commitment.where(user_id: current_user.id)
  end

  # GET /commitments/1 or /commitments/1.json
  def show
  end

  # GET /commitments/new
  def new
    @commitment = Commitment.new
    # @previous_tasks = Task.where(status: 0, commitment: current_user.commitments.last)
  end

  # GET /commitments/1/edit
  def edit
  end

  # POST /commitments or /commitments.json
  def create

    if current_user.commitments.where(active: true).exists?
      flash[:alert] = "Você já tem um compromisso ativo. É permitido apenas um compromisso ativo por vez."
      render :new and return
    end
    
    @commitment = Commitment.new(commitment_params)
    @commitment.user = current_user
    @commitment.active = true

    respond_to do |format|
      if @commitment.save
        format.html { redirect_to root_path, notice: "Compromisso foi criado com sucesso." }
        format.json { render :show, status: :created, location: @commitment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @commitment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commitments/1 or /commitments/1.json
  def update
    respond_to do |format|
      if @commitment.update(commitment_params)
        format.html { redirect_to root_path, notice: "Compromisso foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @commitment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @commitment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commitments/1 or /commitments/1.json
  def destroy
    @commitment.destroy!

    respond_to do |format|
      format.html { redirect_to commitments_path, status: :see_other, notice: "Compromisso foi removido com sucesso." }
      format.json { head :no_content }
    end
  end

  def previous
    @previous_commitments = current_user.commitments.where(active: false).where('created_at <= ?', 7.days.ago).includes(:tasks)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commitment
      @commitment = Commitment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def commitment_params
      params.require(:commitment).permit(:description, :progress)
    end
end

app/views/commitments/_commitment.html.erb
<div id="<%= dom_id commitment %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= commitment.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= commitment.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Progress:</strong>
    <%= commitment.progress %>
  </p>

</div>

app/views/commitments/_form.html.erb
<%= form_with(model: commitment, class: "contents") do |form| %>
  <% if commitment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(commitment.errors.count, "error") %> prohibited this commitment from being saved:</h2>

      <ul>
        <% commitment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :description, "Descrição" %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="text-right">
    <%= form.submit "Criar compromisso", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/commitments/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing commitment</h1>

  <%= render "form", commitment: @commitment %>

  <%= link_to "Show this commitment", @commitment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to commitments", commitments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/commitments/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Commitments" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Commitments</h1>
    <%= link_to "New commitment", new_commitment_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="commitments" class="min-w-full">
    <% @commitments.each do |commitment| %>
      <%= render commitment %>
      <p>
        <%= link_to "Show this commitment", commitment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/commitments/new.html.erb
<div class="mx-auto md:w-2/3 w-full bg-white p-8">
  <h1 class="font-bold text-4xl text-stone-700">Novo compromisso</h1>

  <%= render "form", commitment: @commitment %>
</div>

app/views/commitments/previous.html.erb
<div class="bg-white p-8">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Compromissos anteriores" %>

  <div class="flex justify-between items-center mb-6">
    <h1 class="font-bold text-4xl text-stone-800">Compromissos anteriores</h1>
  </div>

  <div id="previous_commitments" class="w-full">
    <% if @previous_commitments.any? %>
      <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-stone-500 text-white">
          <tr>
            <th class="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">#</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">Descrição do compromisso</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">Data de finalização</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">Progresso</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">Lista de tarefas</th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
          <% @previous_commitments.each_with_index do |previous_commitment, index| %>
            <tr id="<%= dom_id(previous_commitment) %>">
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= index + 1 %></div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= previous_commitment.description %></div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= previous_commitment.updated_at.strftime('%d/%m/%Y') %></div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= number_to_percentage(previous_commitment.progress, precision: @progress_percentage.to_i == @progress_percentage ? 0 : 2, locale: :'pt-BR') %></div>
              </td>
              <td class="px-2 py-4 whitespace-normal break-words max-w-xs">
                <% if previous_commitment.tasks.any? %>
                  <ul class="list-disc ml-5">
                    <% previous_commitment.tasks.each do |task| %>
                      <li class="mb-2 bg-slate-200 p-4 list-none">
                        <strong>Título:</strong> <%= task.title %> <br>
                        <strong>Categoria:</strong> <%= task.category.name %> <br>
                        <strong>Horas:</strong> <%= task.formatted_hours %> <br>
                        <strong>Status:</strong> <%= task.formatted_status %>
                      </li>
                    <% end %>
                  </ul>
                <% else %>
                  <p>Nenhuma tarefa associada</p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>Nenhum compromisso anterior registrado</p>
    <% end %> 
  </div>
</div>

app/views/commitments/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @commitment %>

    <%= link_to "Edit this commitment", edit_commitment_path(@commitment), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to commitments", commitments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this commitment", @commitment, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>