config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  
  get "home/index"
  get 'previous_commitments', to: 'commitments#previous', as: :previous_commitments
  
  resources :tasks do
    get :activities, on: :collection
    member do
      patch 'mark_completed'
      patch 'archive'
      patch 'unarchive'
    end
  end
  
  resources :categories
  resources :commitments
  devise_for :users

  get 'charts', to: 'charts#index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: "Categoria foi criada com sucesso." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: "Categoria foi atualizada com sucesso." }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Categoria foi removida com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, "Nome" %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="text-right">
    <%= form.submit "Cadastrar categoria", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/categories/_modal.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 z-50 transition-opacity duration-300 opacity-0 pointer-events-none" data-controller="modal" data-modal-target="modal" data-action="click->modal#closeWithBackdrop">
    <div class="bg-white rounded-lg overflow-hidden shadow-xl transform transition-all sm:max-w-lg sm:w-full max-h-90vh" data-modal-target="dialog" data-action="click->modal#stopPropagation">
      <div class="bg-stone-800 px-4 py-3 sm:px-6 flex justify-between items-center">
        <h5 class="text-lg leading-6 font-medium text-white"><%= title %></h5>
        <button type="button" class="text-white" data-action="modal#close" aria-label="Close">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="px-4 py-5 sm:p-6 overflow-y-auto" style="max-height: 90vh;" id="modal_body">
        <%= yield %>
      </div>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render "modal", title: "Editar categoria" do %>
  <div class="mx-auto w-full">
    <div class="bg-white">
      <%= render "form", category: @category %>
    </div>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class="bg-white p-8">
  <div class="tab-section rounded-lg min-h-[400px]">
    <% content_for :title, "Categorias" %>

    <div class="flex justify-between items-center mb-6">
      <h1 class="font-bold text-4xl text-stone-800">Categorias</h1>
      <%= link_to "Cadastrar categoria", new_category_path, class: "rounded-lg py-3 px-5 bg-stone-700 hover:bg-stone-800 text-white block font-medium", data: { turbo_frame: "modal" } %>
    </div>

    <div id="categories" class="w-full">
      <% if @categories.any? %>
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-stone-500 text-white">
            <tr>
              <th class="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">Nome</th>
              <th class="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">Ações</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @categories.each do |category| %>
              <tr id="<%= dom_id category %>">
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm text-gray-900"><%= category.name %></div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-left text-sm font-medium">
                  <%= link_to edit_category_path(category), class: "ml-2 rounded-lg py-2 px-4 text-blue-600 hover:bg-gray-100 inline-block font-medium cursor-pointer", data: { turbo_frame: "modal" } do %>
                    <%= lucide_icon('file-pen-line', class: 'inline-block text-blue-600 cursor-pointer') %>
                  <% end %>
                  <%= link_to category, method: :delete, class: "ml-2 rounded-lg py-2 px-4 text-blue-600 hover:bg-gray-100 inline-block font-medium cursor-pointer", data: { turbo_method: :delete, turbo_confirm: "Tem certeza?" } do %>
                    <%= lucide_icon('circle-x', class: 'inline-block text-red-600 cursor-pointer') %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>Nenhum sintoma registrado</p>
      <% end %>
    </div>  
  </div>
</div>

app/views/categories/new.html.erb
<%= render "modal", title: "Cadastrar nova categoria" do %>
  <div class="mx-auto w-full">
    <div class="bg-white">
      <%= render "form", category: @category %>
    </div>
  </div>
<% end %>