config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  
  get "home/index"
  get 'previous_commitments', to: 'commitments#previous', as: :previous_commitments
  
  resources :tasks do
    get :activities, on: :collection
    member do
      patch 'mark_completed'
      patch 'archive'
      patch 'unarchive'
    end
  end
  
  resources :categories
  resources :commitments
  devise_for :users

  get 'charts', to: 'charts#index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Meus Compromissos" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'rails_toastify', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'rails_toastify', 'data-turbo-track': 'reload' %>

    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-slate-200">
    <% if user_signed_in? %>
      <header class="bg-stone-800 text-white h-18">
        <div class="container mx-auto p-4 flex justify-between items-center" style="max-width: 1224px;">
          <section id="top" class="w-full flex justify-between items-center">
            <h2 class="sr-only">Homepage</h2>
            <%= link_to root_path do %>
              <h1><b>MEUS COMPROMISSOS</b></h1>
            <% end %>
            <span id="notification" class="flex items-center mx-4">            
              <% if @available_hours > 1 %>
                <%= lucide_icon('check', class: 'text-green-300 mr-2') %>
                Você tem <%= @formatted_available_hours %>
              <% elsif @available_hours == 1 %>
                <%= lucide_icon('triangle-alert', class: 'text-yellow-300 mr-2') %>
                Você tem <%= @formatted_available_hours %>
              <% else %>
                <%= lucide_icon('x', class: 'text-red-300 mr-2') %>
                Você não tem horas livres no seu dia
              <% end %>
            </span>
            <div class="relative group">
              <a href="<%= edit_user_registration_path %>" id="avatar-profile" class="flex items-center">
                <p class="mr-2 text-end">
                  <b><%= current_user.name %></b>
                  <br />
                  <span class="text-gray-30">Ver perfil</span>
                </p>
                <% if current_user.avatar.present? %>
                  <img src="<%= current_user.avatar %>" class="h-12 w-12 rounded-full border-yellow-500 border-2" />
                <% else %>
                  <%= lucide_icon('user', class: 'h-12 w-12 rounded-full border-yellow-500 border-2') %>
                <% end %>
              </a>

              <div class="absolute right-0 w-48 bg-stone-800 rounded-lg border border-yellow-500 shadow-lg hidden group-hover:block z-50">
                <ul class="py-1">
                  <li>
                    <%= link_to "Compromissos anteriores", previous_commitments_path, class: "block px-4 py-2 text-white  hover:text-gray-300" %>
                  </li>
                  <li>
                    <%= link_to "Listar categorias", categories_path, class: "block px-4 py-2 text-white  hover:text-gray-300" %>
                  </li>
                  <li>
                    <%= link_to "Histórico de atividades", activities_tasks_path, class: "block px-4 py-2 text-white  hover:text-gray-300" %>
                  </li>
                  <li class="border-t border-gray-200"></li>
                  <li>
                    <%= button_to "Sair", destroy_user_session_path, method: :delete, class: "block px-4 py-2 text-yellow-300 hover:text-yellow-600" %>
                  </li>
                </ul>
              </div>
            </div>
          </section>
        </div>
      </header>

      <section id="summary" class="bg-stone-800 text-white h-25">
        <div class="container mx-auto p-4 flex justify-between border-t border-stone-700" style="max-width: 1224px;">
          <h2 class="sr-only">Sumário</h2>
          <div class="grid grid-cols-5">
            <div class="bg-gray p-4 text-yellow-400">
              <strong><%= @total_tasks %></strong>
              Tarefas ao total
            </div>
            <div class="bg-gray p-4 text-blue-400">
              <strong><%= @in_progress %></strong>
              Em andamento
            </div>
            <div class="bg-gray p-4 text-green-400">
              <strong><%= @completed %></strong>
              Concluídas
            </div>
            <div class="bg-gray p-4 text-gray-400">
              <strong><%= @archived %></strong>
              Arquivadas
            </div>
            <div class="bg-gray p-4 text-white">
              <strong><%= number_to_percentage(@progress_percentage, precision: @progress_percentage.to_i == @progress_percentage ? 0 : 2, locale: :'pt-BR') %></strong>
              Progresso
            </div>
          </div>
          <% if current_user.has_active_commitments? %>
            <%= link_to new_task_path, class: "button orange mt-3 inline-flex items-center px-4 py-2 rounded font-bold " + (@available_hours > 0 ? "bg-green-500 text-white hover:bg-green-600" : "cursor-not-allowed pointer-events-none bg-gray-400 text-white"), data: { turbo: (@available_hours > 0).to_s } do %>
              <span class="mr-2">
                <%= lucide_icon('square-plus', class: 'text-white mr-2') %>
              </span>
              Adicionar nova tarefa
            <% end %>
          <% else %>
            <%= link_to new_commitment_path, class: "button orange mt-3 inline-flex items-center bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600 font-bold" do %>
              <span class="mr-2">
                <%= lucide_icon('square-plus', class: 'text-white mr-2') %>
              </span>
              Adicionar novo compromisso
            <% end %>
          <% end %>
        </div>
      </section>

      <main class="mx-auto p-4 items-center" style="max-width: 1224px;">
        <%= yield %>
        <%= rails_toastify_container %>
        <%= rails_toastify_script %>

        <% if notice %>
          <script>
            RailsToastify.show('<%= notice %>',
              { theme: '<%= RailsToastify.configuration.notice_theme %>',
                type: '<%= RailsToastify.configuration.notice_type %>',
                animation: '<%= RailsToastify.configuration.notice_animation %>',
                duration: <%= RailsToastify.configuration.notice_duration %>
              })
          </script>
        <% end %>

        <% if alert %>
          <script>
            RailsToastify.show('<%= alert %>',
              { theme: '<%= RailsToastify.configuration.alert_theme %>',
                type: '<%= RailsToastify.configuration.alert_type %>',
                animation: '<%= RailsToastify.configuration.alert_animation %>',
                duration: <%= RailsToastify.configuration.alert_duration %>
              })
          </script>
        <% end %>

        <%= turbo_frame_tag "modal", target: "_top" %>
        <footer class="w-full text-center text-gray-500 py-4 mt-12">
          © <%= Time.current.year %> <a href="https://eltonmelosantos.com.br/" target="_blank" class="hover:underline">Elton Santos</a>
        </footer>
      </main>
    <% else %>
      <%= yield %>
      <%= rails_toastify_container %>
      <%= rails_toastify_script %>

      <% if notice %>
        <script>
          RailsToastify.show('<%= notice %>',
            { theme: '<%= RailsToastify.configuration.notice_theme %>',
              type: '<%= RailsToastify.configuration.notice_type %>',
              animation: '<%= RailsToastify.configuration.notice_animation %>',
              duration: <%= RailsToastify.configuration.notice_duration %>
            })
        </script>
      <% end %>

      <% if alert %>
        <script>
          RailsToastify.show('<%= alert %>',
            { theme: '<%= RailsToastify.configuration.alert_theme %>',
              type: '<%= RailsToastify.configuration.alert_type %>',
              animation: '<%= RailsToastify.configuration.alert_animation %>',
              duration: <%= RailsToastify.configuration.alert_duration %>
            })
        </script>
      <% end %>   

    <% end %>

  </body>
</html>